projects:
  - repo_url: https://xxxxxxx
    branch: xxx-xxx-xxx
nanoleaf:
  ip:
  authorization_token:
colors:
  success: 00FF00
  in_progress: 00AAAA
  failure: FF0000
  stopped: FFA500
api_key: SOME_REALLY_LONG_SECRET_STRING
